export const QUERY_KEYS = {
  mileageList: 'mileageList',
  submittedMileage: 'submittedMileage',
  isAppliedScholarship: 'isAppliedScholarship',
  scholarshipDuration: 'scholarshipDuration',
  etcMileageList: 'etcMileageList',
  userInfo: 'userInfo',
  capability: 'capability',
  compareCapability: 'compareCapability',
  capabilityDetail: 'capabilityDetail',
  activityRecommend: 'activityRecommend',
  semesterCapability: 'semesterCapability',
  award: 'award',
  faq: 'faq',
  githubStatus: 'githubStatus',
  announcement: 'announcement',
};
