export const QUERY_KEYS = {
  mileageList: 'mileageList',
  submittedMileage: 'submittedMileage',
  isAppliedScholarship: 'isAppliedScholarship',
  scholarshipDuration: 'scholarshipDuration',
  etcMileageList: 'etcMileageList',
  userInfo: 'userInfo',
  portfolioRepositories: 'portfolioRepositories',
  portfolioUserInfo: 'portfolioUserInfo',
  portfolioTechStack: 'portfolioTechStack',
  portfolioMileage: 'portfolioMileage',
  portfolioActivities: 'portfolioActivities',
  portfolioCv: 'portfolioCv',
  portfolioCvShareHtml: 'portfolioCvShareHtml',
  capability: 'capability',
  compareCapability: 'compareCapability',
  capabilityDetail: 'capabilityDetail',
  activityRecommend: 'activityRecommend',
  semesterCapability: 'semesterCapability',
  award: 'award',
  faq: 'faq',
  githubStatus: 'githubStatus',
  announcement: 'announcement',
};
